apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-combo-cm
data:
  NGINX_PORT: "8088"
  nginx.conf: |
      server {
          listen       ${NGINX_PORT};
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
      }
