apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    course: zarf-101
    module: k8s-objects
    topic: configMaps
spec:
  containers:
  - name: nginx-cm
    image: nginx:1.23.1
    command: ["/bin/echo"]
    args: ["$(MESSAGE)", "sleep infinity"]
    ports:
    - containerPort: 8088
    env:
      - name: NGINX_PORT
        valueFrom:
          configMapKeyRef:
            name: nginx-combo-cm
            key: NGINX_PORT
      - name: MESSAGE
        value: "Hello Sparkles"
    volumeMounts:
    - name: config
      mountPath: "/etc/nginx/templates/default.conf.template"
      readOnly: true
      subPath: nginx.conf
  volumes:
  - name: config
    configMap:
      name: nginx-combo-cm
      items:
        - key: nginx.conf
          path: nginx.confi
