apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logstash-daemonset
  labels:
    app: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.14.0
          ports:
            - containerPort: 5000
              name: logstash
       
