apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: podinfo
  name: podinfo
spec:
  ports:
  - name: podinfo
    nodePort: 30080
    port: 9898
    protocol: TCP
    targetPort: 9898
  selector:
    app.kubernetes.io/name: podinfo
  type: NodePort
